url: https://www.pasgah.org

title: "وبلاگ پاسگاه – فهرست تأثیرگذارترین افراد"

description: "فهرست جامع و مقاله‌های اختصاصی دربارهٔ تأثیرگذارترین شخصیت‌های تاریخ از دوران باستان تا امروز"

permalink: /blog/:title

encoding: UTF-8

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
